version: '3.1'

services:
  mysql_db:
    image: mysql:8
    restart: always
    ports:
      - "127.0.0.3:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: dahua
      MYSQL_USER: dahua
      MYSQL_PASSWORD: secret2
    volumes:
      - ./etc/mysql:/etc/mysql/
      - ./data/mysql:/var/lib/mysql/
  redis:
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "127.0.0.3:6379:6379"
    volumes:
      - ./data/redis:/data

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "127.0.0.3:80:80"
      - "127.0.0.3:443:443"
    volumes:
      - ./etc/nginx:/etc/nginx
      - ../app_front/www:/usr/share/nginx/html
